openapi: "3.0.0"
info:
  version: 1.0.0
  title: Home System API

servers:
  - url: http://localhost:8090
    description: Local server

tags:
  - name: "Notifications"
    description: "Notifications endpoints"
  - name: "Notes"
    description: "Notes endpoints"

paths:
  /notifications:
    post:
      tags:
        - "Notifications"
      description: "Прямая отправка письма"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NotificationCreate"
      responses:
        '200':
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StringResponse"

  /notifications/delay:
    post:
      tags:
        - "Notifications"
      description: "Отложенная отправка письма"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NotificationCreateDelayed"

      responses:
        '200':
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StringResponse"
  /notes:
    post:
      tags:
        - "Notes"
      description: "Создание записки"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NotesCreate"
      responses:
        '200':
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StringResponse"

  /notes/{userId}:
    get:
      tags:
        - "Notes"
      description: "Получение записок"
      parameters:
        - name: "userId"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Notes"

components:
  schemas:
    StringResponse:
      type: "object"
      properties:
        result:
          type: "string"

    NotificationCreate:
      type: "object"
      properties:
        notificationType:
          type: "string"
        subject:
          type: "string"
        message:
          type: "string"
        recipient:
          type: "string"

    NotificationCreateDelayed:
      type: "object"
      properties:
        notificationType:
          type: "string"
        subject:
          type: "string"
        message:
          type: "string"
        recipient:
          type: "string"
        dateTime:
          type: "string"
          format: "yyyy-MM-dd'T'HH:mm"

    NotesCreate:
      type: "object"
      properties:
        value:
          type: "string"
        description:
          type: "string"
        telegramUserId:
          type: "number"

    Notes:
      type: "object"
      properties:
        value:
          type: "string"
        description:
          type: "string"
