openapi: "3.0.0"
info:
  version: 1.0.0
  title: Home System API

servers:
  - url: http://localhost:8090
    description: Local server

tags:
  - name: "Notifications"
    description: "Notifications endpoints"

paths:
  /:
    post:
      tags:
        - "Notifications"
      description: "Прямая отправка письма"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NotificationCreate"
      responses:
        '200':
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StringResponse"

components:
  schemas:
    StringResponse:
      type: "object"
      properties:
        result:
          type: "string"

    NotificationCreate:
      type: "object"
      properties:
        notificationType:
          type: "string"
        subject:
          type: "string"
        message:
          type: "string"
        recipient:
          type: "string"
