version: '3.7'

services:
  database:
    build: ./database/
    hostname: database_home_system_major
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: home_system_major
    ports:
      - "6000:5432"
#    volumes:
#      - ./database/create_database_for_docker.sql:/docker-entrypoint-initdb.d/1.sql

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - skynet

  home_system_major:
    restart: always
    container_name: home_system_major
    image: zaytsevdv/home-system-major:dev-latest
    ports:
      - "8090:8090"
    networks:
      - skynet
    environment:
      spring.profiles.active: 'dev-local'
      spring.mail.username: 'user'
      spring.mail.password: 'pass'
      telegram-bot.token: 'token'
      telegram-bot.username: 'my_home_system_bot'
    links:
      - database
    depends_on:
      - database
      - nginx

networks:
  skynet:
    driver: bridge