spring:
  application:
    name: home_system_major

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/home_system_major
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true # to avoid postgres lob creation error at start
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: user
    password: pass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

telegram-bot:
  token: token
  username: my_home_system_bot


server:
  port: 8090

logstash:
  host: localhost
  port: 5000

jwt:
  header: Authorization
  # Base64 with mininum 88 Bits (you can type `echo 'secret-key'|base64` on your command line)
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  #24 hours
  token-validity-in-seconds: 86400
  route:
    authentication:
      path: auth
      refresh: refresh

opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 16686
    service-name: HOME_SYSTEM_MAJOR_APP
    http-sender:
      url: http://localhost:14268/api/traces

management:
  endpoints:
    web:
      exposure:
        include: "*"