spring:
  application:
    name: home_system_major
  mail:
    host: smtp.gmail.com
    port: 587
    username: user
    password: pass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

bot:
  token: token
  username: name

server:
  port: 8080